title: Jekyll Theme Test
email: non-existent@example.com
description: >-
  This is an awesome description of my site.
  It is super cool, and... awesome. No other description can compare
  to the awesomeness and coolness of this description.

baseurl: ""
url: ""

twitter_username: non-existent
github_username: non-existent

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
